trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# ✅ Correct Task Name
- task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- script: echo k8s terraform azure!
  displayName: 'Run a one-line script'

# ✅ Terraform Init
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'Azure subscription 1(0d696f9a-d1f4-4c1b-980d-5a9501ecf1fd)'
    backendAzureRmTenantId: 'ff15dd1b-7224-4d88-8122-54a72fab1081'
    backendAzureRmSubscriptionId: '0d696f9a-d1f4-4c1b-980d-5a9501ecf1fd'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storagemohanxyz'
    backendAzureRmContainerName: 'storageaccountmohancontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true

# ✅ Optional: Download SSH key
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

# ✅ Terraform Init Again (if needed)
- task: TerraformCLI@2
  inputs:
    command: 'init'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    allowTelemetryCollection: true
