trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo KS8 terraform azure!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa1.pub'

# 🔧 Manually export the Terraform path
- script: |
    echo "Adding Terraform to PATH"
    export PATH="/opt/hostedtoolcache/terraform/1.5.7/x64:$PATH"
    terraform version
  displayName: 'Setup Terraform PATH'

# ✅ TerraformCLI task
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resorce-manager-service-connection'
    backendAzureRmTenantId: 'ff15dd1b-7224-4d88-8122-54a72fab1081'
    backendAzureRmSubscriptionId: '0d696f9a-d1f4-4c1b-980d-5a9501ecf1fd'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctmohanxyz'
    backendAzureRmContainerName: 'storageacctmohan'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
