trigger:
  branches:
    include:
      - main  # or your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'

stages:
  - stage: Terraform
    jobs:
      - job: TerraformJob
        steps:
         # Checkout the code
         - checkout: self

         # ✅ Install Terraform using Microsoft DevLabs task
         - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
           displayName: 'Install Terraform'
           inputs:
             terraformVersion: '1.7.5'

         # ✅ Terraform Init
         - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
           displayName: 'Terraform Init'
           inputs:
             provider: 'azurerm'
             command: 'init'
             workingDirectory: '$(terraformWorkingDir)'
             backendServiceArm: 'azure-resorce-manager-service-connection'
             backendAzureRmResourceGroupName: 'terraform-backend-rg'
             backendAzureRmStorageAccountName: 'storageacctmohanxyz'
             backendAzureRmContainerName: 'storageacctmohan'
             backendAzureRmKey: 'kubernetes-dev.tfstate'

         # ✅ Terraform Plan
         - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
           displayName: 'Terraform Plan'
           inputs:
             provider: 'azurerm'
             command: 'plan'
             workingDirectory: '$(terraformWorkingDir)'
             environmentServiceNameAzureRM: 'azure-resorce-manager-service-connection'

         # ✅ Terraform Apply
         - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
           displayName: 'Terraform Apply'
           inputs:
             provider: 'azurerm'
             command: 'apply'
             workingDirectory: '$(terraformWorkingDir)'
             environmentServiceNameAzureRM: 'azure-resorce-manager-service-connection'
             commandOptions: '-auto-approve'