trigger:
  - main

variables:
  ARM_CLIENT_ID: '89f6f348-1d68-44b7-b962-98cff07d0c8b'
  ARM_TENANT_ID: 'ff15dd1b-7224-4d88-8122-54a72fab1081'
  ARM_SUBSCRIPTION_ID: '0d696f9a-d1f4-4c1b-980d-5a9501ecf1fd'
  TF_BACKEND_RESOURCE_GROUP: 'terraform-backend-rg'
  TF_BACKEND_STORAGE_ACCOUNT: 'storagemohanxyz'
  TF_BACKEND_CONTAINER_NAME: 'storageaccountmohancontainer'
  TF_STATE_KEY: 'kubernetes-dev.tfstate'

stages:
  - stage: TerraformDeploy
    jobs:
      - job: Deploy
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          # ✅ Download the client secret as a secure file (private key or secret)
          - task: DownloadSecureFile@1
            name: clientSecretFile
            inputs:
              secureFile: 'azure1-rsa.pub'  # Make sure this matches the uploaded secure file name

          # ✅ Export the secure file content as environment variable (client secret)
          - script: |
              echo "Reading secure file content..."
              export ARM_CLIENT_SECRET=$(cat $(clientSecretFile.secureFilePath))
              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$ARM_CLIENT_SECRET"
            displayName: 'Export client secret from secure file'

          # ✅ Install Terraform CLI (Fix ambiguity using full task name)
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: '1.5.7'  # Recommended version

          # ✅ Terraform Init with remote backend config
          - script: |
              terraform init \
                -backend-config="storage_account_name=$(TF_BACKEND_STORAGE_ACCOUNT)" \
                -backend-config="container_name=$(TF_BACKEND_CONTAINER_NAME)" \
                -backend-config="key=$(TF_STATE_KEY)" \
                -backend-config="resource_group_name=$(TF_BACKEND_RESOURCE_GROUP)" \
                -backend-config="subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                -backend-config="tenant_id=$(ARM_TENANT_ID)" \
                -backend-config="client_id=$(ARM_CLIENT_ID)" \
                -backend-config="client_secret=$(ARM_CLIENT_SECRET)"
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
            displayName: 'Terraform Init'

          # ✅ Terraform Plan
          - script: terraform plan
            displayName: 'Terraform Plan'

          # ✅ Terraform Apply
          - script: terraform apply -auto-approve
            displayName: 'Terraform Apply'
