trigger: none  # Prevent accidental runs

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Starting EKS Cluster Destruction Process"
  displayName: 'Starting Destroy Process'

# Install Terraform
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

# Terraform Init
- task: TerraformTask@5
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-mohan-123'
    backendAWSKey: 'kubernetes-dev.tfstate'
    commandOptions: '-reconfigure'

# Terraform Destroy ONLY
- task: TerraformTask@5
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'
    commandOptions: '-auto-approve'  # Add this to avoid manual confirmation